pipeline:
  name: aks-deployment
  identifier: aksdeployment
  projectIdentifier: akswebapi
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Dev
        identifier: Dev
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: akswebapiservice
          environment:
            environmentRef: dev_1681976941706
            deployToAll: false
            infrastructureDefinitions:
              - identifier: devcluster_1681976941706
          execution:
            steps:
              - step:
                  name: Rollout Deployment
                  identifier: rolloutDeployment
                  type: K8sRollingDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
